apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wordpress

type: Opaque
stringData:
  db_user: vinod
  db_password: vinod@123
  PGADMIN_DEFAULT_EMAIL: admin@example.com
  PGADMIN_DEFAULT_PASSWORD: admin123
